<template>
  <div class="analysis-view">
    <n-card title="Industry Analysis" size="small">
      <n-space vertical>
        <n-text>Research reports generated by AI analysis.</n-text>
        <StatusView
          :status="status"
          :error="error"
          :on-retry="reload"
          empty-description="No analysis reports yet"
        >
          <n-grid cols="1 s:2 m:3" responsive="screen" :x-gap="12" :y-gap="12">
            <n-gi v-for="report in reports" :key="report.id">
              <n-card size="small" hoverable @click="showReport(report)">
                <template #header>{{ report.title || 'Untitled' }}</template>
                <n-text depth="3">{{ report.date }} | {{ report.analyst }}</n-text>
              </n-card>
            </n-gi>
          </n-grid>
        </StatusView>
      </n-space>
    </n-card>

    <n-modal
      v-model:show="showModal"
      preset="card"
      style="width: 80%"
      title="Report Detail"
    >
      <div
        v-if="showModal && modalContent"
        class="modal-markdown-body"
        v-html="renderedModalContent"
      />
    </n-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import MarkdownIt from 'markdown-it'
import { NCard, NSpace, NText, NGrid, NGi, NModal } from 'naive-ui'
import StatusView from '../components/common/StatusView.vue'
import { toFetchError, type FetchError } from '../utils/fetchError'
import api from '../api/client'
import type { ResearchReport } from '../types/report'

const md = new MarkdownIt()

const loading = ref(false)
const error = ref<FetchError | null>(null)
const reports = ref<ResearchReport[]>([])
const showModal = ref(false)
const modalContent = ref('')

const renderedModalContent = computed(() => md.render(modalContent.value))

/**
 * Derived render status for StatusView. Precedence: loading > error > empty >
 * idle. Only `idle` yields the default slot (the report grid), so a fetch
 * failure or in-flight request never renders stale cards behind it.
 */
const status = computed<'idle' | 'loading' | 'empty' | 'error'>(() => {
  if (loading.value) return 'loading'
  if (error.value) return 'error'
  if (reports.value.length === 0) return 'empty'
  return 'idle'
})

function showReport(report: ResearchReport) {
  modalContent.value = report.content || ''
  showModal.value = true
}

/**
 * Fetch the analysis reports. Re-used as the StatusView Retry handler: on a
 * fresh attempt we clear the previous error so the derived status flips back to
 * loading and the operator gets immediate feedback rather than a stuck error
 * panel. Any thrown value is normalized into the shared { code, message }
 * vocabulary so StatusView renders it identically to SSE failures.
 */
async function reload() {
  loading.value = true
  error.value = null
  try {
    const { data } = await api.get('/analysis/reports')
    reports.value = data.reports
  } catch (e) {
    error.value = toFetchError(e)
  } finally {
    loading.value = false
  }
}

onMounted(reload)
</script>

<style scoped>
.analysis-view { padding: 16px; height: 100%; }

.modal-markdown-body {
  padding: 12px 16px;
  color: var(--dgm-text-muted);
}
.modal-markdown-body :deep(h1),
.modal-markdown-body :deep(h2),
.modal-markdown-body :deep(h3) {
  margin: 16px 0 8px;
  color: var(--dgm-text);
}
.modal-markdown-body :deep(p) {
  margin: 8px 0;
  line-height: 1.6;
}
.modal-markdown-body :deep(code) {
  background: var(--dgm-border);
  padding: 2px 6px;
  border-radius: 3px;
  font-size: 13px;
}
.modal-markdown-body :deep(pre) {
  background: rgba(0, 0, 0, 0.3);
  padding: 12px;
  border-radius: 6px;
  overflow-x: auto;
}
.modal-markdown-body :deep(pre code) {
  background: none;
  padding: 0;
}
.modal-markdown-body :deep(ul),
.modal-markdown-body :deep(ol) {
  padding-left: 20px;
}
.modal-markdown-body :deep(table) {
  border-collapse: collapse;
  width: 100%;
}
.modal-markdown-body :deep(th),
.modal-markdown-body :deep(td) {
  border: 1px solid var(--dgm-table-border);
  padding: 6px 10px;
  text-align: left;
}
</style>
