<template>
  <div class="analysis-view">
    <n-card title="Industry Analysis" size="small">
      <n-space vertical>
        <n-text>Research reports generated by AI analysis.</n-text>
        <n-spin :show="loading">
          <n-grid cols="1 s:2 m:3" responsive="screen" :x-gap="12" :y-gap="12">
            <n-gi v-for="report in reports" :key="report.id">
              <n-card size="small" hoverable @click="showReport(report)">
                <template #header>{{ report.title || 'Untitled' }}</template>
                <n-text depth="3">{{ report.date }} | {{ report.analyst }}</n-text>
              </n-card>
            </n-gi>
          </n-grid>
        </n-spin>
      </n-space>
    </n-card>

    <n-modal
      v-model:show="showModal"
      preset="card"
      style="width: 80%"
      title="Report Detail"
    >
      <div
        v-if="showModal && modalContent"
        class="modal-markdown-body"
        v-html="renderedModalContent"
      />
    </n-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import MarkdownIt from 'markdown-it'
import { NCard, NSpace, NText, NGrid, NGi, NModal, NSpin } from 'naive-ui'
import api from '../api/client'
import type { ResearchReport } from '../types/report'

const md = new MarkdownIt()

const loading = ref(false)
const reports = ref<ResearchReport[]>([])
const showModal = ref(false)
const modalContent = ref('')

const renderedModalContent = computed(() => md.render(modalContent.value))

function showReport(report: ResearchReport) {
  modalContent.value = report.content || ''
  showModal.value = true
}

onMounted(async () => {
  loading.value = true
  try {
    const { data } = await api.get('/analysis/reports')
    reports.value = data.reports
  } finally {
    loading.value = false
  }
})
</script>

<style scoped>
.analysis-view { padding: 16px; height: 100%; }

.modal-markdown-body {
  padding: 12px 16px;
  color: rgba(255, 255, 255, 0.82);
}
.modal-markdown-body :deep(h1),
.modal-markdown-body :deep(h2),
.modal-markdown-body :deep(h3) {
  margin: 16px 0 8px;
  color: rgba(255, 255, 255, 0.95);
}
.modal-markdown-body :deep(p) {
  margin: 8px 0;
  line-height: 1.6;
}
.modal-markdown-body :deep(code) {
  background: rgba(255, 255, 255, 0.08);
  padding: 2px 6px;
  border-radius: 3px;
  font-size: 13px;
}
.modal-markdown-body :deep(pre) {
  background: rgba(0, 0, 0, 0.3);
  padding: 12px;
  border-radius: 6px;
  overflow-x: auto;
}
.modal-markdown-body :deep(pre code) {
  background: none;
  padding: 0;
}
.modal-markdown-body :deep(ul),
.modal-markdown-body :deep(ol) {
  padding-left: 20px;
}
.modal-markdown-body :deep(table) {
  border-collapse: collapse;
  width: 100%;
}
.modal-markdown-body :deep(th),
.modal-markdown-body :deep(td) {
  border: 1px solid #3a3b52;
  padding: 6px 10px;
  text-align: left;
}
</style>
