"""Workspace & Workflow facade."""

from doge.application.use_cases.capability_registry import BuildCapabilityRegistry
from doge.core.domain.platform_models import (
    CaseAssetLink,
    CaseDecision,
    CaseRunLink,
    Project,
    ResearchCase,
    TemplatePreflightResult,
    WorkflowTemplate,
    WorkflowExecution,
    WorkflowTemplateRunLink,
    Workspace,
    to_dict,
)
from doge.core.domain.workflow_template import TemplateRunInput, build_template_run_request
from doge.core.ports.capability_provider import ICapabilityProvider
from doge.core.ports.platform_repository import IPlatformRepository
from doge.platform.workspace.application import (
    CaseAssetCreate,
    CaseAssetService,
    CaseDecisionCreate,
    CaseDecisionService,
    CaseExecutionCreate,
    CaseExecutionCreateResult,
    CaseExecutionService,
    CaseRunCreate,
    CaseRunCreateResult,
    PlatformAccessDeniedError,
    PlatformFeatureDisabledError,
    PlatformNotFoundError,
    PlatformRequestContext,
    PlatformServiceError,
    PlatformValidationError,
    ProjectService,
    ResearchCaseService,
    WorkflowService,
    WorkspaceService,
)
from doge.platform.workspace.template_seed import BUILTIN_TEMPLATES, TemplateSeedResult, seed_workflow_templates

__all__ = [
    "BuildCapabilityRegistry",
    "BUILTIN_TEMPLATES",
    "CaseAssetCreate",
    "CaseAssetService",
    "CaseAssetLink",
    "CaseDecision",
    "CaseDecisionCreate",
    "CaseDecisionService",
    "CaseExecutionCreate",
    "CaseExecutionCreateResult",
    "CaseExecutionService",
    "CaseRunCreate",
    "CaseRunCreateResult",
    "CaseRunLink",
    "ICapabilityProvider",
    "IPlatformRepository",
    "PlatformAccessDeniedError",
    "PlatformFeatureDisabledError",
    "PlatformNotFoundError",
    "PlatformRequestContext",
    "PlatformServiceError",
    "PlatformValidationError",
    "Project",
    "ProjectService",
    "ResearchCase",
    "ResearchCaseService",
    "TemplateRunInput",
    "TemplatePreflightResult",
    "TemplateSeedResult",
    "WorkflowExecution",
    "WorkflowTemplate",
    "WorkflowTemplateRunLink",
    "WorkflowService",
    "Workspace",
    "WorkspaceService",
    "build_template_run_request",
    "seed_workflow_templates",
    "to_dict",
]
