"""Compatibility facade for workspace application services."""

from doge.platform.workspace.application.case_service import (
    CaseAssetCreate,
    CaseDecisionCreate,
    CaseExecutionCreate,
    CaseExecutionCreateResult,
    CaseRunCreate,
    CaseRunCreateResult,
    PlatformAccessDeniedError,
    PlatformAccessService,
    PlatformFeatureDisabledError,
    PlatformNotFoundError,
    PlatformRequestContext,
    PlatformServiceError,
    PlatformValidationError,
    ProjectService,
    ResearchCaseService,
    WorkflowService,
    WorkspaceService,
)

__all__ = [
    "CaseAssetCreate",
    "CaseDecisionCreate",
    "CaseExecutionCreate",
    "CaseExecutionCreateResult",
    "CaseRunCreate",
    "CaseRunCreateResult",
    "PlatformAccessDeniedError",
    "PlatformAccessService",
    "PlatformFeatureDisabledError",
    "PlatformNotFoundError",
    "PlatformRequestContext",
    "PlatformServiceError",
    "PlatformValidationError",
    "ProjectService",
    "ResearchCaseService",
    "WorkflowService",
    "WorkspaceService",
]
