"""Generate the documentation status rollup.

The output is deterministic: it is derived from local repo files and does not
include wall-clock timestamps. Use ``--check`` in CI to verify that
``docs/quality/status.md`` is up to date.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "quality" / "status.md"
ARCHITECTURE = ROOT / "docs" / "registry" / "architecture.yaml"
MATURITY = ROOT / "docs" / "progress" / "runtime-maturity.yaml"
SPRINT_STATUS = ROOT / "production" / "sprint-status.yaml"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if output is stale")
    args = parser.parse_args(argv)

    content = render_status()
    if args.check:
        if not OUTPUT.exists():
            print(f"missing generated file: {_display(OUTPUT)}")
            return 1
        existing = OUTPUT.read_text(encoding="utf-8")
        if existing != content:
            print(f"stale generated file: {_display(OUTPUT)}")
            print("run: python scripts/generate_docs_status.py")
            return 1
        print(f"up to date: {_display(OUTPUT)}")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {_display(OUTPUT)}")
    return 0


def render_status() -> str:
    systems = _parse_block_items(ARCHITECTURE, "systems")
    superseded = _parse_block_items(ARCHITECTURE, "superseded_systems")
    maturity = MATURITY.read_text(encoding="utf-8")
    sprint = SPRINT_STATUS.read_text(encoding="utf-8")

    production_ready = _search_value(maturity, r"\bproduction_ready:\s*([^\n]+)")
    stable_declaration = _search_value(maturity, r"\bstable_declaration:\s*([^\n]+)")
    level_1 = _search_value(maturity, r"\blevel_1_embedded_cli_session:\s*([^\n]+)")
    level_2 = _search_value(maturity, r"\blevel_2_daemon_gateway:\s*([^\n]+)")
    level_3 = _search_value(maturity, r"\blevel_3_sdk_platform:\s*([^\n]+)")
    active_sprint = _search_value(sprint, r"\nrollup:\n\s+sprint:\s*([^\n]+)")
    total_stories = _search_value(sprint, r"\n\s+total_stories:\s*([^\n]+)")

    lines = [
        "# Documentation Status",
        "",
        "This file is generated by `scripts/generate_docs_status.py`. Do not edit it by hand.",
        "",
        "## Architecture Registry",
        "",
        f"- Canonical active systems: {len(systems)}",
        f"- Superseded historical systems: {len(superseded)}",
        "- Canonical authority: `docs/architecture/adr-0021-bounded-context-consolidation.md`",
        "- Directory migration authority: `docs/architecture/adr-0022-directory-restructuring.md`",
        "",
        "### Active Systems",
        "",
        "| # | System | Classification | Status |",
        "|---|--------|----------------|--------|",
    ]
    for item in systems:
        lines.append(
            f"| {item.get('num', '')} | {item.get('name', '')} | "
            f"{item.get('classification', item.get('category', ''))} | {item.get('status', '')} |"
        )

    lines.extend(
        [
            "",
            "## Runtime Maturity",
            "",
            f"- Level 1 embedded CLI/session: `{level_1}`",
            f"- Level 2 daemon gateway: `{level_2}`",
            f"- Level 3 SDK/platform: `{level_3}`",
            f"- production_ready: `{production_ready}`",
            f"- stable_declaration: `{stable_declaration}`",
            "",
            "The status above is intentionally non-production unless the maturity file changes.",
            "",
            "## Sprint Rollup",
            "",
            f"- Active sprint: `{active_sprint}`",
            f"- Total stories in rollup: `{total_stories}`",
            "",
            "## Documentation Gates",
            "",
            "- README points to `docs/index.md`.",
            "- Dated 2026-06-23 audit snapshots live under `docs/archive/audits/`.",
            "- Legacy product reference paths (`docs/API.md`, `docs/CLI.md`, `docs/MCP_SERVER.md`) remain compatible.",
            "- `docs/progress/runtime-maturity.yaml` remains the maturity authority.",
            "",
        ]
    )
    return "\n".join(lines)


def _parse_block_items(path: Path, key: str) -> list[dict[str, str]]:
    text = path.read_text(encoding="utf-8").splitlines()
    in_block = False
    items: list[dict[str, str]] = []
    for line in text:
        if not in_block:
            if line == f"{key}:":
                in_block = True
            continue
        if line and not line.startswith(" ") and not line.startswith("#"):
            break
        stripped = line.strip()
        if stripped.startswith("- {") and stripped.endswith("}"):
            items.append(_parse_inline_mapping(stripped[3:-1]))
    return items


def _parse_inline_mapping(text: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for part in re.split(r",\s+(?=[A-Za-z_][A-Za-z0-9_-]*:)", text):
        if ":" not in part:
            continue
        key, value = part.split(":", 1)
        result[key.strip()] = value.strip().strip('"')
    return result


def _search_value(text: str, pattern: str) -> str:
    match = re.search(pattern, text)
    return match.group(1).strip().strip('"') if match else "unknown"


def _display(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


if __name__ == "__main__":
    sys.exit(main())
