"""Report compatibility-surface counts as a versioned trend.

Parses ``docs/architecture/compatibility-surfaces.md`` and reports the
``current_count`` of each registered surface. Counts are heterogeneous (public
callables, Python files, route decorators, classes, ...), so this tool reports
**per surface** and **subtotals per unit** only — it never sums across units
into a single meaningless total.

Modes:
  --check   Parse and print; exit non-zero if any surface's ``current_count``
            lacks a leading integer. Does not modify the tree (CI-safe).
  --write   Additionally append a timestamped report section to
            ``docs/quality/compatibility-count.md`` (committed, versioned trend).

Default (no flag) is ``--check``.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "docs" / "architecture" / "compatibility-surfaces.md"
REPORT = ROOT / "docs" / "quality" / "compatibility-count.md"

_COUNT_RE = re.compile(r"^\s*(\d+)\s*(.*)")


@dataclass(frozen=True)
class SurfaceCount:
    surface: str
    count: int
    unit: str


@dataclass(frozen=True)
class ParseFailure:
    surface: str
    raw: str


def parse(path: Path | None = None) -> tuple[list[SurfaceCount], list[ParseFailure]]:
    if path is None:
        path = REGISTRY
    rows = _surface_rows(path.read_text(encoding="utf-8"))
    counts: list[SurfaceCount] = []
    failures: list[ParseFailure] = []
    if not rows:
        return counts, failures
    headers = rows[0]
    if "surface" not in headers or "current_count" not in headers:
        return counts, failures
    surface_idx = headers.index("surface")
    count_idx = headers.index("current_count")
    for row in rows[1:]:
        if len(row) != len(headers):
            continue
        surface = row[surface_idx]
        raw = row[count_idx]
        match = _COUNT_RE.match(raw)
        if not match:
            failures.append(ParseFailure(surface, raw))
            continue
        counts.append(SurfaceCount(surface, int(match.group(1)), _normalize_unit(match.group(2))))
    return counts, failures


def _normalize_unit(rest: str) -> str:
    rest = re.split(r"[,.;:()]", rest)[0].strip()
    words = rest.split()[:2]
    unit = "-".join(w.lower() for w in words)
    if not unit:
        return "unit"
    # crude singularize the last segment so "files"/"file" group together
    parts = unit.split("-")
    if len(parts[-1]) > 2 and parts[-1].endswith("s"):
        parts[-1] = parts[-1][:-1]
    return "-".join(parts)


def render(counts: list[SurfaceCount], failures: list[ParseFailure]) -> str:
    lines = ["| surface | count | unit |", "|---|---|---|"]
    for c in sorted(counts, key=lambda x: x.surface):
        lines.append(f"| `{c.surface}` | {c.count} | {c.unit} |")

    by_unit: dict[str, list[SurfaceCount]] = {}
    for c in counts:
        by_unit.setdefault(c.unit, []).append(c)
    lines += ["", "Per-unit subtotals (never summed across units):",
              "| unit | subtotal | surfaces |", "|---|---|---|"]
    for unit in sorted(by_unit):
        group = by_unit[unit]
        lines.append(f"| {unit} | {sum(c.count for c in group)} | {len(group)} |")

    if failures:
        lines += ["", "Parse failures (current_count must start with an integer):"]
        for f in failures:
            lines.append(f"- `{f.surface}`: {f.raw.strip()!r}")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    if not args.check and not args.write:
        args.check = True

    counts, failures = parse()
    report = render(counts, failures)

    if args.write:
        REPORT.parent.mkdir(parents=True, exist_ok=True)
        stamp = date.today().isoformat()
        section = f"\n## {stamp}\n\n{report}\n"
        if REPORT.exists():
            REPORT.write_text(REPORT.read_text(encoding="utf-8").rstrip() + "\n" + section, encoding="utf-8")
        else:
            REPORT.write_text(
                "# Compatibility Surface Count Trend\n\n"
                "> Generated by `scripts/report_compatibility_count.py --write`. "
                "Do not edit by hand; rerun the script to refresh.\n" + section,
                encoding="utf-8",
            )
        print(f"wrote {_display(REPORT)}")
        return 0 if not failures else 1

    # --check (default)
    print(report)
    if failures:
        print("\ncompatibility count check FAILED: some surfaces lack a leading integer")
        return 1
    print("\ncompatibility count check passed")
    return 0


def _display(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return str(path)


def _surface_rows(text: str) -> list[list[str]]:
    """Return the Surface Registry table rows (header + data) as cell lists."""
    lines = text.splitlines()
    rows: list[list[str]] = []
    in_table = False
    for line in lines:
        if line.strip() == "## Surface Registry":
            in_table = True
            continue
        if in_table and line.startswith("## "):
            break
        if not in_table or not line.startswith("|"):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if set(cells) == {"---"}:
            continue
        rows.append(cells)
    return rows


if __name__ == "__main__":
    sys.exit(main())
