"""Application package root."""

from doge.application import contracts, use_cases
from doge.application.composition import (
    build_anomaly_service,
    build_breadth_service,
    build_catalog_use_case,
    build_generate_anomaly_report_use_case,
    build_generate_industry_report_use_case,
    build_generate_macro_report_use_case,
    build_agent_document_repository,
    build_agent_repositories,
    build_agent_runtime_kernel,
    build_append_turn_use_case,
    build_create_session_use_case,
    build_execute_run_use_case,
    build_kimi_agent_model,
    build_list_sessions_use_case,
    build_persisted_research_agent_runtime,
    build_research_agent_runtime,
    build_resume_run_use_case,
    build_resume_session_use_case,
    build_generate_market_overview_use_case,
    build_industry_report_use_case,
    build_manage_notes_use_case,
    build_metadata_source,
    build_note_repository,
    build_stock_name_repository,
    build_populate_stock_names_use_case,
    build_query_ticker_use_case,
    build_ranking_service,
    build_report_repository,
    build_scan_market_use_case,
    build_schema_browser,
    build_stock_repository,
    build_stock_service,
    build_view_repository,
    build_view_service,
    refresh_views,
)

__all__ = [
    "contracts",
    "use_cases",
    # factories
    "build_view_repository",
    "build_view_service",
    "build_stock_repository",
    "build_stock_service",
    "build_report_repository",
    "build_schema_browser",
    "build_note_repository",
    "build_stock_name_repository",
    "build_metadata_source",
    "build_ranking_service",
    "build_breadth_service",
    "build_anomaly_service",
    "refresh_views",
    # use-case factories
    "build_scan_market_use_case",
    "build_generate_macro_report_use_case",
    "build_agent_document_repository",
    "build_agent_repositories",
    "build_agent_runtime_kernel",
    "build_append_turn_use_case",
    "build_create_session_use_case",
    "build_execute_run_use_case",
    "build_kimi_agent_model",
    "build_list_sessions_use_case",
    "build_persisted_research_agent_runtime",
    "build_research_agent_runtime",
    "build_resume_run_use_case",
    "build_resume_session_use_case",
    "build_manage_notes_use_case",
    "build_query_ticker_use_case",
    "build_generate_market_overview_use_case",
    "build_generate_anomaly_report_use_case",
    "build_generate_industry_report_use_case",
    "build_industry_report_use_case",
    "build_catalog_use_case",
    "build_populate_stock_names_use_case",
]
